#Requires -Version 5.1
<#
.SYNOPSIS
  DayZ local test launcher — build + deploy + filepatching launch on DayZDiag_x64.exe.

.DESCRIPTION
  Operationalizes DAYZ_INFRA.md. Optionally builds the mod PBO with AddonBuilder,
  deploys it to the P:\Mods junction (-> DayZ\!Workshop), and launches DayZDiag in
  offline / server / client / all modes with -filePatching.

  Path resolution order (DAYZ_INFRA.md seccion "Variables de entorno opcionales (resolvers)"): DAYZ_* env var -> Steam default.

.PARAMETER Mod
  Mod name (CfgPatches identifier, no dashes). Drives @<Mod>, P:\<Mod> source, PBO name.

.PARAMETER Mode
  offline = single DayZDiag with -mission, no network     [DESIGN — validate in-game]
  server  = dedicated DayZDiag -server only               [EXACT]
  client  = DayZDiag connecting to 127.0.0.1              [EXACT]
  all     = server, wait for bind, then client (default)  [EXACT]

.PARAMETER Mission
  Alias (chernarus|livonia|sakhal) or an absolute path to a mission folder.

.PARAMETER Build
  Re-pack the PBO with AddonBuilder before launching (needed when assets/scripts changed).

.PARAMETER Clean
  Pass -clear to AddonBuilder (wipe target dir first). Implies -Build.

.NOTES
  Generated by skill dayz-test-ingame. Lives in <Mod>_dev\tools\.
  Flags marked [EXACT] verified against DAYZ_INFRA.md. Offline mode is [DESIGN].
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)] [string]$Mod,
    [ValidateSet('offline', 'server', 'client', 'all')] [string]$Mode = 'all',
    [string]$Mission = 'chernarus',
    [string]$Source,
    [string]$ExtraMods = '',
    [string]$BaseMods = '@CF;@Dabs Framework;@VPPAdminTools',
    [string]$ServerMods = '',
    [switch]$NoBaseMods,
    [int]$Port = 2302,
    [int]$Width = 1920,
    [int]$Height = 1080,
    [string]$PlayerName = 'Dev',
    [string]$AdminSteamId = '',
    [string]$AdminPass = 'dayzadmin',
    [int]$ServerWait = 60,
    [switch]$Build,
    [switch]$Clean,
    [switch]$PackOnly,
    [switch]$Retail,
    [switch]$NoFilePatching,
    [switch]$Preflight,
    [switch]$Kill,
    [string]$RunId = ''
)

$ErrorActionPreference = 'Stop'

function Info($m) { Write-Host "[dayz-test] $m" -ForegroundColor Cyan }
function Ok($m)   { Write-Host "   [ok] $m"     -ForegroundColor Green }
function Warn($m) { Write-Host "   [warn] $m"   -ForegroundColor Yellow }
function Die($m)  { Write-Host "   [FAIL] $m"   -ForegroundColor Red; exit 1 }

# ---------------------------------------------------------------------------
# Path resolution: env var override -> Steam default (DAYZ_INFRA.md seccion "Variables de entorno opcionales (resolvers)")
# ---------------------------------------------------------------------------
$SteamCommon   = 'C:\Program Files (x86)\Steam\steamapps\common'
$GamePath      = if ($env:DAYZ_GAME_PATH)  { $env:DAYZ_GAME_PATH }  else { Join-Path $SteamCommon 'DayZ' }
$DiagExe       = if ($env:DAYZ_DIAG_PATH)  { $env:DAYZ_DIAG_PATH }  else { Join-Path $GamePath 'DayZDiag_x64.exe' }
$RetailExe     = Join-Path $GamePath 'DayZ_x64.exe'
$ToolsPath     = if ($env:DAYZ_TOOLS_PATH) { $env:DAYZ_TOOLS_PATH } else { Join-Path $SteamCommon 'DayZ Tools' }
$AddonBuilder  = Join-Path $ToolsPath 'Bin\AddonBuilder\AddonBuilder.exe'
$ServerInstall = Join-Path $SteamCommon 'DayZServer'
$Workshop      = Join-Path $GamePath '!Workshop'
$WorkDrive     = if ($env:DAYZ_WORK_DRIVE) { $env:DAYZ_WORK_DRIVE } else { 'P:\' }
$ModsDir       = Join-Path $WorkDrive 'Mods'

# Diag is mandatory for -filePatching past the loading screen (DAYZ_INFRA.md seccion "Diag binary obligatorio para iteracion").
$Exe = if ($Retail) { $RetailExe } else { $DiagExe }
# Retail game exe cannot run headless: DayZ_x64 -server dies loading GFX resources
# (Water/*.edds) after CE boot. Retail server = the dedicated binary.
# (verified 2026-06-11, A6_MK47 session)
$DedicatedExe = 'C:\Program Files (x86)\Steam\steamapps\common\DayZServer\DayZServer_x64.exe'
$ServerExe = if ($Retail -and (Test-Path $DedicatedExe)) { $DedicatedExe } else { $Exe }

# Dev workspace = parent of this script's folder (we live in <Mod>_dev\tools\).
$DevRoot        = Split-Path -Parent $PSScriptRoot
$ServerWs       = Join-Path $DevRoot '_server'
$ClientWs       = Join-Path $DevRoot '_client'
$ServerCfg      = Join-Path $ServerWs 'serverDZ.cfg'
$ServerProfiles = Join-Path $ServerWs 'profiles'
$ClientProfiles = Join-Path $ClientWs 'profiles'

$MissionMap = @{ chernarus = 'dayzOffline.chernarusplus'; livonia = 'dayzOffline.enoch'; sakhal = 'dayzOffline.sakhal' }

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
function Stop-DayZ {
    if ([string]::IsNullOrWhiteSpace($script:RunId)) {
        Die '-Kill requires the exact non-empty -RunId.'
    }
    $result = Invoke-LifecycleCli -Command 'stop' -TargetRunId $script:RunId
    if (-not $result.ok -or $result.state -ne 'EXITED') {
        Die 'Managed lifecycle stop did not return EXITED.'
    }
    Ok "Managed run_id $script:RunId is EXITED."
}

$LifecycleTools = 'C:\Users\guill\OneDrive\Documentos\DayZ Projects\DayZ_MCP_dev\tools'
$LifecyclePython = 'C:\Users\guill\OneDrive\Documentos\DayZ Projects\DayZ_MCP_dev\tools\.venv-mcp\Scripts\python.exe'
$LifecycleKeyfile = 'C:\Users\guill\OneDrive\Documentos\DayZ Projects\DayZ_MCP_dev\tools\.dayz_mcp.key'
$LifecyclePort = 8765
$script:RunId = $RunId
$script:LifecycleClientIdentityJson = $null
$script:LifecycleLeaseToken = $null

function Initialize-LifecycleCredentials {
    $identity = [Environment]::GetEnvironmentVariable('DAYZ_MCP_CLIENT_ID_JSON', 'Process')
    $lease = [Environment]::GetEnvironmentVariable('DAYZ_MCP_LEASE_TOKEN', 'Process')
    if (-not [string]::IsNullOrWhiteSpace($identity)) {
        $script:LifecycleClientIdentityJson = $identity
    }
    if (-not [string]::IsNullOrWhiteSpace($lease)) {
        $script:LifecycleLeaseToken = $lease
    }
    [Environment]::SetEnvironmentVariable('DAYZ_MCP_CLIENT_ID_JSON', $null, 'Process')
    [Environment]::SetEnvironmentVariable('DAYZ_MCP_LEASE_TOKEN', $null, 'Process')
}

function Assert-LifecycleEnvironment {
    if (
        [string]::IsNullOrWhiteSpace($script:LifecycleClientIdentityJson) -or
        [string]::IsNullOrWhiteSpace($script:LifecycleLeaseToken)
    ) {
        Die 'Managed lifecycle environment is incomplete.'
    }
    if (-not (Test-Path -LiteralPath $LifecyclePython -PathType Leaf)) {
        Die 'Managed lifecycle Python is unavailable.'
    }
    if (-not (Test-Path -LiteralPath $LifecycleKeyfile -PathType Leaf)) {
        Die 'Managed lifecycle keyfile is unavailable.'
    }
}

function Invoke-LifecycleCli {
    param(
        [ValidateSet('start', 'stop', 'adopt', 'status')] [string]$Command,
        [string]$RequestPath = '',
        [string]$TargetRunId = ''
    )
    Assert-LifecycleEnvironment
    $cliArgs = @('-m', 'dayz_mcp.lifecycle_cli', '--keyfile', $LifecycleKeyfile, '--port', [string]$LifecyclePort, $Command)
    if ($Command -eq 'start') { $cliArgs += @('--request-file', $RequestPath) }
    if ($Command -in @('stop', 'adopt')) { $cliArgs += @('--run-id', $TargetRunId) }

    $raw = @()
    $exitCode = 2
    $previousIdentity = [Environment]::GetEnvironmentVariable('DAYZ_MCP_CLIENT_ID_JSON', 'Process')
    $previousLease = [Environment]::GetEnvironmentVariable('DAYZ_MCP_LEASE_TOKEN', 'Process')
    [Environment]::SetEnvironmentVariable('DAYZ_MCP_CLIENT_ID_JSON', $script:LifecycleClientIdentityJson, 'Process')
    [Environment]::SetEnvironmentVariable('DAYZ_MCP_LEASE_TOKEN', $script:LifecycleLeaseToken, 'Process')
    try {
        Push-Location $LifecycleTools
        try {
            $raw = @(& $LifecyclePython @cliArgs 2>&1)
            $exitCode = $LASTEXITCODE
        } finally {
            Pop-Location
        }
    } finally {
        [Environment]::SetEnvironmentVariable('DAYZ_MCP_CLIENT_ID_JSON', $previousIdentity, 'Process')
        [Environment]::SetEnvironmentVariable('DAYZ_MCP_LEASE_TOKEN', $previousLease, 'Process')
    }

    $result = $null
    try {
        $result = (($raw | ForEach-Object { [string]$_ }) -join [Environment]::NewLine) | ConvertFrom-Json
    } catch {
        if ($exitCode -eq 0) { Die 'Managed lifecycle returned invalid JSON.' }
    }
    if ($exitCode -ne 0) {
        $reason = if ($result -and $result.error) { [string]$result.error } else { 'request_failed' }
        Die "Managed lifecycle '$Command' failed (exit $exitCode, reason=$reason)."
    }
    if (-not $result) { Die 'Managed lifecycle returned no JSON result.' }
    return $result
}

function Invoke-ManagedStart {
    param(
        [string[]]$Argv,
        [string]$Cwd,
        [string]$Role,
        [string]$WindowStyle,
        [string]$Label,
        [string]$Profiles,
        [string]$MissionValue,
        [string]$ExtendRunId = ''
    )
    $request = [ordered]@{
        argv = @($Argv)
        cwd = $Cwd
        role = $Role
        window_style = $WindowStyle
        label = $Label
        mod = "@$Mod"
        profiles = $Profiles
        mission = $MissionValue
    }
    if ($ExtendRunId) { $request.run_id = $ExtendRunId }
    $requestPath = Join-Path ([System.IO.Path]::GetTempPath()) ("dayz-mcp-lifecycle-{0}.json" -f [guid]::NewGuid().ToString('N'))
    try {
        $utf8 = [System.Text.UTF8Encoding]::new($false)
        [System.IO.File]::WriteAllText($requestPath, ($request | ConvertTo-Json -Depth 5 -Compress), $utf8)
        $result = Invoke-LifecycleCli -Command 'start' -RequestPath $requestPath
    } finally {
        if (Test-Path -LiteralPath $requestPath) {
            Remove-Item -LiteralPath $requestPath -Force -ErrorAction SilentlyContinue
        }
    }
    if (-not $result.ok -or [string]::IsNullOrWhiteSpace([string]$result.run_id)) {
        Die 'Managed lifecycle start did not return a public run_id.'
    }
    $script:RunId = [string]$result.run_id
}

function Adopt-DayZRun {
    if ([string]::IsNullOrWhiteSpace($script:RunId)) {
        Die 'A non-empty -RunId is required to adopt a managed run.'
    }
    $result = Invoke-LifecycleCli -Command 'adopt' -TargetRunId $script:RunId
    if (-not $result.ok -or $result.state -ne 'RUNNING') {
        Die 'Managed lifecycle adopt did not return RUNNING.'
    }
    $script:RunId = [string]$result.run_id
}

function Resolve-Mission {
    param([string]$M)
    if ([System.IO.Path]::IsPathRooted($M)) {
        if (Test-Path $M) { return (Resolve-Path $M).Path }
        Die "Mission path not found: $M"
    }
    $folder = $MissionMap[$M.ToLower()]
    if (-not $folder) { Die "Unknown mission alias '$M'. Use chernarus|livonia|sakhal or an absolute path." }
    # Workspace copy first (lets you edit init.c/types.xml), then the server install template.
    $candidates = @(
        (Join-Path $ServerWs "mpmissions\$folder"),
        (Join-Path $ServerInstall "mpmissions\$folder")
    )
    foreach ($c in $candidates) { if (Test-Path $c) { return (Resolve-Path $c).Path } }
    Die "Mission '$folder' not found in workspace or DayZServer install. Reinstall DayZServer (appid 223350) or copy the mission to $ServerWs\mpmissions\."
}

function New-ServerCfg {
    param([string]$Path, [string]$Template)
    $missionFolder = Split-Path -Leaf $Template
    $body = @"
// Generated by dayz-test-ingame. Local dev only.
hostname        = "DEV $Mod";
maxPlayers      = 10;
verifySignatures = 0;          // dev: do not enforce .bisign
allowFilePatching = 1;         // MANDATORY for -filePatching clients (DAYZ_INFRA.md seccion "serverDZ.cfg"; BattlEye 0x00020005 otherwise)
disableVoN      = 1;
disable3rdPerson = 0;
instanceId      = 1;
storageAutoFix  = 1;
serverTimePersistent = 0;
vppDisablePassword = 1;        // VPP AdminTools: skip the admin password so a SuperAdmins.txt superadmin opens the menu directly. Verified vs VPP source missionServer.c:14 / PermissionManager.c (2026-06-09). Remove for password-protected testing.

class Missions
{
    class DayZ
    {
        template = "$missionFolder";
    };
};
"@
    Set-Content -Path $Path -Value $body -Encoding ASCII
}

function Initialize-VppSuperadmin {
    # VPP superadmin seeding. Layouts differ across VPP versions:
    #   (a) <profiles>\VPPAdminTools\SuperAdmins.json -> {"SUPER_ADMINS":[...]}
    #   (b) <profiles>\VPPAdminTools\Permissions\ (newer, the installed one here):
    #       SuperAdmins\SuperAdmins.txt (one SteamID64 per line) + credentials.txt (login
    #       password on line 1, hashed at first boot, raw then lost). Version (b) IGNORES the
    #       JSON, so seed BOTH. SteamID: -AdminSteamId else retail config. (verified 2026-06-09)
    if ((Get-ModString) -notlike '*VPPAdminTools*') { return }
    $vppDir = Join-Path $ServerProfiles 'VPPAdminTools'

    $ids = @()
    if ($AdminSteamId) { $ids = @($AdminSteamId) }
    else {
        $existing = Join-Path $env:LOCALAPPDATA 'DayZ\VPPAdminTools\SuperAdmins.json'
        if (Test-Path $existing) {
            try { $ids = @((Get-Content $existing -Raw | ConvertFrom-Json).SUPER_ADMINS) } catch { $ids = @() }
        }
    }
    if (-not $ids -or $ids.Count -eq 0) {
        Warn 'No admin SteamID. Pass -AdminSteamId, or set %LOCALAPPDATA%\DayZ\VPPAdminTools\SuperAdmins.json. VPP boots with no superadmin.'
        return
    }

    # (a) legacy JSON — harmless for versions that ignore it; seed only if absent.
    $json = Join-Path $vppDir 'SuperAdmins.json'
    if (-not (Test-Path $json)) {
        New-Item -ItemType Directory -Force -Path $vppDir | Out-Null
        (@{ SUPER_ADMINS = @($ids) } | ConvertTo-Json) | Set-Content -Path $json -Encoding ASCII
    }

    # (b) Permissions\ layout — what the installed VPP actually reads.
    $saTxt = Join-Path $vppDir 'Permissions\SuperAdmins\SuperAdmins.txt'
    New-Item -ItemType Directory -Force -Path (Split-Path $saTxt) | Out-Null
    # Collect candidate IDs (existing file lines + resolved ids), keep ONLY clean 17-digit
    # SteamID64 tokens, dedup. Validating each token prevents string-concatenation corruption
    # and self-heals a previously corrupted file (e.g. two IDs joined into one 34-digit line).
    $merged = [System.Collections.Generic.List[string]]::new()
    $candidates = @()
    if (Test-Path $saTxt) { $candidates += @(Get-Content $saTxt) }
    $candidates += @($ids)
    foreach ($c in $candidates) {
        $s = "$c".Trim()
        if ($s -match '^\d{17}$' -and -not $merged.Contains($s)) { $merged.Add($s) }
    }
    Set-Content -Path $saTxt -Value ($merged -join "`r`n") -Encoding ASCII
    Ok "VPP superadmin(s) -> $saTxt ($($merged -join ', '))"

    # credentials.txt: login password on line 1, hashed by VPP at first boot. Seed only when not
    # already set, so an existing hash or user-chosen password is never clobbered.
    $cred = Join-Path $vppDir 'Permissions\credentials.txt'
    $needsPass = $true
    if (Test-Path $cred) {
        $first = (Get-Content $cred | Select-Object -First 1)
        if ($first -match '^[0-9A-Fa-f]{64}$') { $needsPass = $false }
        elseif ($first -and $first.Trim() -and ($first -notmatch '^\s*//')) { $needsPass = $false }
    }
    if ($needsPass) {
        New-Item -ItemType Directory -Force -Path (Split-Path $cred) | Out-Null
        Set-Content -Path $cred -Value $AdminPass -Encoding ASCII
        Ok "VPP login password set -> '$AdminPass' (VPP hashes it at boot; store it, the raw is then lost)"
    }
    else { Ok 'VPP credentials.txt already set (not overwriting)' }
}

# ---------------------------------------------------------------------------
# Preflight (DAYZ_INFRA.md secciones "Layout de drives y mods" + "Diag binary" + "serverDZ.cfg")
# ---------------------------------------------------------------------------
function Invoke-Preflight {
    Info 'Preflight...'

    if (-not (Test-Path $Exe)) {
        Die "Game exe not found: $Exe`n       Set DAYZ_GAME_PATH / DAYZ_DIAG_PATH, or verify the DayZ install."
    }
    Ok "exe: $Exe"
    if (-not $Retail -and ($Exe -notlike '*DayZDiag*')) {
        Warn 'Not using DayZDiag — retail exe blocks past the loading screen with -filePatching.'
    }

    if (-not (Test-Path $WorkDrive)) { Die "Work drive $WorkDrive not mounted. See DAYZ_INFRA.md (P:\ symlink)." }
    Ok "work drive: $WorkDrive"

    # P:\Mods MUST be a junction to <DayZ>\!Workshop so deployed PBOs land where the engine reads.
    if (-not (Test-Path $ModsDir)) {
        Warn "$ModsDir missing. Creating junction -> $Workshop"
        & cmd /c mklink /J "$ModsDir" "$Workshop" | Out-Null
        if (-not (Test-Path $ModsDir)) { Die "Failed to create junction $ModsDir." }
        Ok "junction created: $ModsDir -> $Workshop"
    }
    else {
        $item = Get-Item $ModsDir -Force
        if ($item.LinkType -eq 'Junction') { Ok "junction ok: $ModsDir" }
        else { Warn "$ModsDir exists but is NOT a junction. Deployed mods may not be seen by the engine." }
    }

    # Server workspace + serverDZ.cfg with allowFilePatching = 1.
    if ($Mode -in @('server', 'client', 'all')) {
        if (-not (Test-Path $ServerWs)) { New-Item -ItemType Directory -Force -Path $ServerWs | Out-Null }
        if (-not (Test-Path $ServerProfiles)) { New-Item -ItemType Directory -Force -Path $ServerProfiles | Out-Null }
        if (-not (Test-Path $ServerCfg)) {
            New-ServerCfg -Path $ServerCfg -Template $script:MissionPath
            Ok "generated serverDZ.cfg (allowFilePatching=1): $ServerCfg"
        }
        else {
            $cfg = Get-Content $ServerCfg -Raw
            if ($cfg -match 'allowFilePatching\s*=\s*1') { Ok 'serverDZ.cfg: allowFilePatching = 1' }
            else { Die "serverDZ.cfg has allowFilePatching != 1 -> BattlEye kick 0x00020005. Fix: $ServerCfg" }
            # Self-heal: cfgs generated before the vppDisablePassword default (pre 2026-06-09) lack it,
            # leaving a VPP superadmin stuck at the password prompt. Append it if absent.
            if ($cfg -notmatch 'vppDisablePassword') {
                Add-Content -Path $ServerCfg -Value 'vppDisablePassword = 1;        // auto-added: VPP passwordless admin for SuperAdmins.txt superadmins (dev). Remove for password-gated testing.'
                Ok 'serverDZ.cfg: appended vppDisablePassword = 1 (VPP passwordless admin)'
            }
            else { Ok 'serverDZ.cfg: vppDisablePassword present' }
        }
        Initialize-VppSuperadmin
    }
    if ($Mode -in @('offline', 'client', 'all')) {
        if (-not (Test-Path $ClientProfiles)) { New-Item -ItemType Directory -Force -Path $ClientProfiles | Out-Null }
    }

    if ($Build -or $Clean) {
        if (-not (Test-Path $AddonBuilder)) { Die "AddonBuilder not found: $AddonBuilder (set DAYZ_TOOLS_PATH)." }
        Ok "AddonBuilder: $AddonBuilder"
    }

    Ok "mission: $script:MissionPath"
    Info 'Preflight passed.'
}

# ---------------------------------------------------------------------------
# Build + deploy (DAYZ_INFRA.md seccion "Comandos de invocacion canonicos" - AddonBuilder)
# ---------------------------------------------------------------------------
function Invoke-Build {
    $src = if ($Source) { $Source } else { Join-Path $WorkDrive $Mod }
    if (-not (Test-Path $src)) { Die "Mod source not found: $src (pass -Source, or junction P:\$Mod -> your editable folder)." }
    $target = Join-Path $ModsDir "@$Mod\Addons"
    $temp   = Join-Path $WorkDrive "temp\$Mod"
    if (-not (Test-Path $target)) { New-Item -ItemType Directory -Force -Path $target | Out-Null }

    # AddonBuilder's incremental sync to $temp can serve STALE source: a changed .c may
    # silently not be re-copied (observed 2026-06-18: a deviceinspector.c months out of date
    # was packed into the PBO, so script edits never reached the build and the diag kept
    # compiling old code — a fix appeared to "not take" across several rebuilds). Wipe the
    # temp staging before every build so the sync is always fresh. Costs incremental reuse
    # (full re-binarize) but a stale build is a silent correctness disaster that masks edits.
    if (Test-Path $temp) { Remove-Item -LiteralPath $temp -Recurse -Force -ErrorAction SilentlyContinue }

    # AddonBuilder's default (binarize) mode does NOT copy .c scripts (not in its include-list):
    # a scripts-only mod then packs to a config-only PBO and nothing runs in-game. Use -packonly
    # (copies all as-is) when the source has no binarizable assets, or force it with -PackOnly.
    # Verified 2026-06-03 (a scripts mod packed to 662 b under binarize, 124 KB under -packonly).
    $hasAssets   = @(Get-ChildItem $src -Recurse -Include *.p3d, *.paa, *.rvmat -File -ErrorAction SilentlyContinue).Count -gt 0
    $usePackOnly = $PackOnly -or (-not $hasAssets)

    Info "Build: $src -> $target$(if ($usePackOnly) { ' (-packonly)' })"
    $abArgs = @("`"$src`"", "`"$target`"", "-prefix=$Mod", "`"-temp=$temp`"")
    if ($Clean) { $abArgs += '-clear' }
    if ($usePackOnly) { $abArgs += '-packonly' }
    $p = Start-Process -FilePath $AddonBuilder -ArgumentList $abArgs -Wait -NoNewWindow -PassThru
    if ($p.ExitCode -ne 0) { Die "AddonBuilder failed (exit $($p.ExitCode)). Check config.cpp / paths." }
    $pbo = Join-Path $target "$Mod.pbo"
    if (-not (Test-Path $pbo)) { Die "Build reported success but $pbo is missing." }
    # Sanity: a mod with scripts that packs tiny means binarize dropped the .c (include-list).
    if ((Test-Path (Join-Path $src 'scripts')) -and ((Get-Item $pbo).Length -lt 4096)) {
        Warn "PBO is only $((Get-Item $pbo).Length) b but the mod has scripts\ - binarize likely dropped the .c. Re-run with -PackOnly."
    }
    Ok "deployed: $pbo ($((Get-Item $pbo).Length) b)"
}

# ---------------------------------------------------------------------------
# Launch
# ---------------------------------------------------------------------------
function Resolve-ModToken {
    # A bare '@Name' is resolved by the engine relative to its cwd (the game dir), i.e.
    # <DayZ>\@Name — which does NOT exist; deployed mods live under <DayZ>\!Workshop\@Name.
    # The engine then silently fails to mount that addon (its CfgPatches/CfgVehicles never
    # register, so CreateObjectEx returns null with NO error). Verified 2026-06-01 via an
    # in-mission ConfigIsExisting probe: '@LFQuad' relative -> CfgPatches absent; the same
    # mod as an absolute !Workshop path -> present. So: rewrite each bare '@Name' to its
    # absolute !Workshop path when that folder exists. Absolute/rooted tokens pass through.
    param([string]$Token)
    $t = $Token.Trim()
    if (-not $t) { return $null }
    if ([System.IO.Path]::IsPathRooted($t)) { return $t }
    $abs = Join-Path $Workshop $t
    if (Test-Path -LiteralPath $abs) { return $abs }
    return $t   # not in !Workshop (e.g. a mod folder elsewhere) — leave as-is
}

function Get-ModString {
    # Load order: dependencies first (CF must be leftmost), then this mod, then extras.
    $parts = @()
    if (-not $NoBaseMods -and $BaseMods) { $parts += ($BaseMods -split ';') }
    $parts += "@$Mod"
    if ($ExtraMods) { $parts += ($ExtraMods -split ';') }
    $resolved = @()
    foreach ($p in $parts) { $r = Resolve-ModToken $p; if ($r) { $resolved += $r } }
    return ($resolved -join ';')
}

function Wait-ServerBind {
    param([int]$TimeoutSec)
    if ([string]::IsNullOrWhiteSpace($script:RunId)) {
        Warn 'Exact managed run_id is unavailable; refusing readiness.'
        return $false
    }
    Info "Waiting for exact managed server run to bind UDP $Port (max ${TimeoutSec}s)..."
    $deadline = (Get-Date).AddSeconds($TimeoutSec)
    while ((Get-Date) -lt $deadline) {
        $status = Invoke-LifecycleCli -Command 'status'
        $matchingRuns = @($status.runs | Where-Object { [string]$_.run_id -eq [string]$script:RunId })
        if ($matchingRuns.Count -ne 1) {
            Warn 'Exact managed run is missing or ambiguous.'
            return $false
        }
        $run = $matchingRuns[0]
        if ([string]$run.state -ne 'RUNNING') {
            Warn 'Exact managed run is not RUNNING.'
            return $false
        }
        $serverRecords = @($run.processes | Where-Object { [string]$_.role -eq 'server' })
        if ($serverRecords.Count -eq 0) {
            Warn 'Exact managed run has no server-role process.'
            return $false
        }
        $serverPids = @()
        foreach ($record in $serverRecords) {
            [int]$parsedPid = 0
            if (-not [int]::TryParse([string]$record.pid, [ref]$parsedPid) -or $parsedPid -le 0) {
                Warn 'Exact managed run has an invalid server PID.'
                return $false
            }
            $serverPids += $parsedPid
        }
        $uniqueServerPids = @($serverPids | Sort-Object -Unique)
        if ($uniqueServerPids.Count -ne $serverPids.Count) {
            Warn 'Exact managed run has ambiguous server PIDs.'
            return $false
        }
        foreach ($serverPid in $uniqueServerPids) {
            if (-not (Get-Process -Id $serverPid -ErrorAction SilentlyContinue)) {
                Warn 'Exact managed server process exited before binding.'
                return $false
            }
        }
        $bound = @(Get-NetUDPEndpoint -LocalPort $Port -ErrorAction SilentlyContinue)
        if ($bound.Count -gt 0) {
            $foreign = @($bound | Where-Object { [int]$_.OwningProcess -notin $uniqueServerPids })
            if ($foreign.Count -gt 0) {
                Warn 'UDP port is bound by a process outside the exact managed run.'
                return $false
            }
            $owned = @($bound | Where-Object { [int]$_.OwningProcess -in $uniqueServerPids })
            if ($owned.Count -gt 0) {
                Ok 'Exact managed server is listening.'
                return $true
            }
        }
        Start-Sleep -Seconds 2
    }
    Warn 'Timed out waiting for the exact managed server bind.'
    return $false
}

function Start-Server {
    $argv = @($DiagExe, '-server', "-config=$ServerCfg", "-profiles=$ServerProfiles", "-mission=$script:MissionPath", "-mod=$(Get-ModString)")
    if (-not $NoFilePatching) { $argv += '-filePatching' }
    $argv += "-port=$Port"
    if ($ServerMods) {
        $sm = (($ServerMods -split ';') | ForEach-Object { Resolve-ModToken $_ }) -join ';'
        $argv += "-serverMod=$sm"
    }
    Info "Requesting managed SERVER for @$Mod."
    Invoke-ManagedStart -Argv $argv -Cwd $GamePath -Role 'server' -WindowStyle 'normal' -Label "@$Mod server" -Profiles $ServerProfiles -MissionValue $script:MissionPath
}

function Start-Client {
    $argv = @($DiagExe, "-mod=$(Get-ModString)", '-connect=127.0.0.1', "-port=$Port", "-profiles=$ClientProfiles", "-name=$PlayerName", '-window', "-x=$Width", "-y=$Height")
    if (-not $NoFilePatching) { $argv += '-filePatching' }
    Info "Requesting managed CLIENT for @$Mod."
    Invoke-ManagedStart -Argv $argv -Cwd $GamePath -Role 'client' -WindowStyle 'normal' -Label "@$Mod client" -Profiles $ClientProfiles -MissionValue $script:MissionPath -ExtendRunId $script:RunId
}

function Start-Offline {
    $argv = @($DiagExe, "-mod=$(Get-ModString)", "-mission=$script:MissionPath", "-profiles=$ClientProfiles", '-window', "-x=$Width", "-y=$Height")
    if (-not $NoFilePatching) { $argv += '-filePatching' }
    Info "Requesting managed OFFLINE [DESIGN] for @$Mod."
    Invoke-ManagedStart -Argv $argv -Cwd $GamePath -Role 'offline' -WindowStyle 'normal' -Label "@$Mod offline" -Profiles $ClientProfiles -MissionValue $script:MissionPath -ExtendRunId $script:RunId
}

function Show-VppHint {
    if ((Get-ModString) -notlike '*VPPAdminTools*') { return }
    $f = Join-Path $ServerProfiles 'VPPAdminTools\SuperAdmins.json'
    Info 'VPP admin tools loaded.'
    Write-Host "   superadmin file: $f" -ForegroundColor Cyan
    Write-Host '   format: {"SUPER_ADMINS":["<SteamID64>"]} — restart the server after editing.' -ForegroundColor Cyan
}

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
if ($Retail) { Die 'Retail lifecycle is manual-only and quarantined; no build or launch was started.' }
Initialize-LifecycleCredentials
if ($Kill) { Stop-DayZ; exit 0 }
if ($Clean) { $Build = $true }

$script:MissionPath = Resolve-Mission -M $Mission
Invoke-Preflight
if ($Preflight) { Info 'Preflight only — exiting.'; exit 0 }
if ($Mode -in @('server', 'all') -and $RunId) { Die 'server/all reject an input RunId because they create a new managed run.' }
if ($Mode -eq 'client' -and [string]::IsNullOrWhiteSpace($RunId)) { Die 'client requires the exact -RunId to adopt.' }
if ($Build) { Invoke-Build } else { Info 'Skipping build (-Build to re-pack the PBO).' }

switch ($Mode) {
    'offline' { if ($RunId) { Adopt-DayZRun }; Start-Offline }
    'server'  { Start-Server }
    'client'  { Adopt-DayZRun; Start-Client }
    'all'     {
        Start-Server
        if (Wait-ServerBind -TimeoutSec $ServerWait) { Start-Client }
        else { Die 'Exact managed server readiness failed; refusing client launch.' }
    }
}
if ($Mode -in @('server', 'all')) { Show-VppHint }

Info "Managed run_id: $script:RunId. Mode '$Mode' for @$Mod. Logs: server=$ServerProfiles  client=$ClientProfiles"
Info 'The caller owns release/status; keep the lease only for active exclusive work and verify status before handoff.'
Info 'Stuck? Use -Kill -RunId <exact-id>; never scan or terminate another session.'
