"""Offline Steam startup mitigation and public remediation branch diagnostics."""
from __future__ import annotations

import ctypes
from datetime import datetime
import io
from pathlib import Path
from types import SimpleNamespace
import sys
import unittest
from unittest.mock import AsyncMock, Mock, patch

from dayz_mcp import steam_preflight as sp
from tests import test_steamfastpath_repair as fast


STARTED_AT = datetime(2026, 9, 9, 12, 53, 4).timestamp()
NOW = datetime(2026, 9, 9, 12, 55, 24).timestamp()
# Literal event observed in Steam's console_log.txt:2264, not generated by the parser.
MARKER = b"[2026-09-09 12:53:18] System startup time: 13.36 seconds\r\n"
OLD_MARKER = b"[2026-09-09 03:15:52] System startup time: 5.77 seconds\r\n"


class SteamStartupWaitTests(unittest.TestCase):
    def setUp(self):
        self.provider = fast.MemoryProvider()
        self.host = fast.MemoryHost(self.provider)
        self.probe = Mock(return_value=False)
        self.provider.steam_startup_complete = self.probe
        self.enterContext(patch.object(sp, "_STARTUP_WAIT_S", 0.65))
        self.popen = self.enterContext(patch.object(
            sp.subprocess, "Popen", side_effect=AssertionError("Real launch forbidden")
        ))
        self.enterContext(patch.object(
            sp.WindowsSteamPreflightProvider, "read_active_process",
            side_effect=AssertionError("Real registry forbidden"),
        ))
        self.enterContext(patch.object(
            sp.WindowsSteamRemediationHost, "write_active_process_pid",
            side_effect=AssertionError("Real registry write forbidden"),
        ))
        self.enterContext(patch.object(
            sp, "_kernel32", side_effect=AssertionError("Real process query forbidden")
        ))

    def tearDown(self):
        self.popen.assert_not_called()

    def run_remediation(self):
        return sp.remediate_stale_steam_session(self.provider, self.host)

    def test_coherent_registry_without_startup_marker_times_out(self):
        self.provider.pid = 41
        self.assertIsNone(sp.evaluate_steam_session(self.provider).error_code)
        result = self.run_remediation()
        self.assertEqual(result.error_code, "steam_session_stale")
        self.assertEqual(result.steam_remediation_reason, "startup_timeout")
        self.assertEqual(self.host.now, 0.65)
        self.assertEqual(self.host.invocations, [])
        self.assertEqual(self.host.writes, [])
        self.assertEqual(result.steam_pid_repair_reason, "already_correct")
        self.assertFalse(result.steam_restart_fallback)
        self.assertGreater(self.probe.call_count, 1)

    def test_applied_pid_repair_waits_for_startup_marker(self):
        self.probe.side_effect = lambda pid: self.host.now >= 0.6
        result = self.run_remediation()
        self.assertIsNone(result.error_code)
        self.assertGreaterEqual(self.host.now, 0.6)
        self.assertLessEqual(self.host.now, 0.65)
        self.assertEqual(self.host.writes, [41])
        self.assertEqual(self.host.invocations, [])
        self.assertEqual(result.steam_pid_repair_reason, "applied")
        self.assertFalse(result.steam_restart_fallback)
        self.assertEqual({call.args for call in self.probe.call_args_list}, {(41,)})

    def test_already_correct_pid_waits_for_startup_marker(self):
        self.provider.pid = 41
        self.probe.side_effect = lambda pid: self.host.now >= 0.4
        result = self.run_remediation()
        self.assertIsNone(result.error_code)
        self.assertEqual(self.host.now, 0.4)
        self.assertEqual(self.host.writes, [])
        self.assertEqual(self.host.invocations, [])
        self.assertEqual(result.steam_pid_repair_reason, "already_correct")

    def test_restart_waits_after_registry_match_and_preserves_branch(self):
        self.host.write_error = PermissionError()
        self.probe.side_effect = lambda pid: self.host.now >= 0.6
        result = self.run_remediation()
        self.assertIsNone(result.error_code)
        self.assertGreaterEqual(self.host.now, 0.6)
        self.assertEqual(result.steam_pid_repair_reason, "write_failed")
        self.assertTrue(result.steam_restart_fallback)
        self.assertEqual([args for _, args in self.host.invocations],
                         [("-shutdown",), ("-silent",)])

    def test_restart_with_coherent_registry_but_no_marker_fails(self):
        self.host.write_error = PermissionError()
        result = self.run_remediation()
        self.assertEqual(result.error_code, "steam_session_stale")
        self.assertEqual(result.steam_remediation_reason, "startup_timeout")
        self.assertTrue(result.steam_restart_fallback)
        self.assertFalse(result.steam_left_down)
        self.assertEqual(len(self.host.invocations), 2)
        self.assertEqual(self.host.now, 0.65)

    def test_already_completed_startup_does_not_sleep(self):
        self.probe.return_value = True
        result = self.run_remediation()
        self.assertIsNone(result.error_code)
        self.assertEqual(self.host.now, 0)
        self.probe.assert_called_once_with(41)

    def test_legacy_provider_without_capability_fails_before_mutation(self):
        for capability in (None, False):
            with self.subTest(capability=capability):
                self.provider.steam_startup_complete = capability
                result = self.run_remediation()
                self.assertEqual(result.error_code, "steam_session_stale")
                self.assertEqual(result.steam_remediation_reason, "startup_probe_unavailable")
                self.assertEqual(self.host.write_attempts, [])
                self.assertEqual(self.host.invocations, [])
                self.assertEqual(self.host.now, 0)
                self.assertFalse(result.steam_restart_fallback)
        legacy = SimpleNamespace(**{
            name: getattr(self.provider, name) for name in (
                "read_active_process", "process_exists", "process_image_path", "steam_process_pids"
            )
        })
        result = sp.remediate_stale_steam_session(legacy, self.host)
        self.assertEqual(result.steam_remediation_reason, "startup_probe_unavailable")
        self.assertEqual(self.host.invocations, [])

    def test_probe_error_fails_closed_without_private_diagnostics(self):
        self.probe.side_effect = OSError("private account 987654321")
        result = self.run_remediation()
        self.assertEqual(result.error_code, "steam_session_stale")
        self.assertEqual(result.steam_remediation_reason, "startup_probe_failed")
        self.assertEqual(self.host.now, 0.65)
        self.assertNotIn("987654321", repr(result))
        self.assertEqual(self.host.invocations, [])

    def test_non_boolean_probe_result_cannot_become_success(self):
        for value in (None, 1, 0, "ready", object()):
            with self.subTest(value=value):
                self.host.now = 0
                self.probe.return_value = value
                result = self.run_remediation()
                self.assertEqual(result.error_code, "steam_session_stale")
                self.assertEqual(result.steam_remediation_reason, "startup_probe_failed")
                self.assertEqual(self.host.now, 0.65)

    def test_probe_can_recover_from_transient_read_error_within_budget(self):
        self.probe.side_effect = [PermissionError(), False, True]
        result = self.run_remediation()
        self.assertIsNone(result.error_code)
        self.assertEqual(self.host.now, 0.4)

    def test_probe_success_after_deadline_is_rejected_without_extra_read(self):
        def delayed(pid):
            self.host.now = 0.7
            return True
        self.probe.side_effect = delayed
        result = self.run_remediation()
        self.assertEqual(result.error_code, "steam_session_stale")
        self.assertEqual(result.steam_remediation_reason, "startup_timeout")
        self.probe.assert_called_once_with(41)
        self.assertEqual(self.host.now, 0.7)

    def test_registry_change_during_probe_is_not_accepted(self):
        def change_registry(pid):
            self.provider.pid = 88
            return True
        self.probe.side_effect = change_registry
        result = self.run_remediation()
        self.assertEqual(result.error_code, "steam_session_stale")
        self.assertEqual(result.steam_remediation_reason, "startup_session_changed")
        self.assertEqual(self.host.invocations, [])
        self.assertEqual(self.host.writes, [41])
        self.probe.assert_called_once_with(41)

    def test_dead_or_additional_process_during_probe_cannot_pass(self):
        for defect in ("dead", "additional"):
            with self.subTest(defect=defect):
                self.provider = fast.MemoryProvider()
                self.host = fast.MemoryHost(self.provider)
                def changed(pid):
                    if defect == "dead":
                        self.provider.existing.clear()
                    else:
                        self.provider.pids = (41, 42)
                    return True
                self.provider.steam_startup_complete = changed
                result = self.run_remediation()
                self.assertEqual(result.error_code, "steam_session_stale")
                self.assertEqual(result.steam_remediation_reason, "startup_session_changed")
                self.assertEqual(self.host.now, 0.65)
                self.assertEqual(self.host.invocations, [])


class RecordingStream(io.BytesIO):
    def __init__(self, content):
        super().__init__(content)
        self.read_sizes = []

    def read(self, size=-1):
        self.read_sizes.append(size)
        return super().read(size)


class WindowsSteamStartupTests(unittest.TestCase):
    def setUp(self):
        self.handle = 2**40 + 41
        self.started_at = STARTED_AT
        self.image_path = r"C:\Steam\steam.exe"
        self.exit_code = 259
        self.native = SimpleNamespace(
            OpenProcess=Mock(return_value=self.handle), CloseHandle=Mock(),
            GetProcessTimes=Mock(side_effect=self.get_times),
            QueryFullProcessImageNameW=Mock(side_effect=self.get_image),
            GetExitCodeProcess=Mock(side_effect=self.get_exit),
        )
        self.bind_native = sp._kernel32
        self.enterContext(patch.object(sp, "_kernel32", return_value=self.native))
        self.enterContext(patch.object(sp.time, "time", return_value=NOW))
        self.popen = self.enterContext(patch.object(
            sp.subprocess, "Popen", side_effect=AssertionError("Real launch forbidden")
        ))
        self.registry = SimpleNamespace(
            OpenKey=Mock(side_effect=AssertionError("Real registry forbidden")),
            SetValueEx=Mock(side_effect=AssertionError("Real registry write forbidden")),
        )
        self.enterContext(patch.dict(sys.modules, {"winreg": self.registry}))
        self.provider = sp.WindowsSteamPreflightProvider()

    def tearDown(self):
        self.popen.assert_not_called()
        self.registry.OpenKey.assert_not_called()
        self.registry.SetValueEx.assert_not_called()

    def get_times(self, handle, created, exited, kernel, user):
        self.assertEqual(handle, self.handle)
        ticks = round(self.started_at * 10_000_000) + 116444736000000000
        target = ctypes.cast(created, ctypes.POINTER(sp.wintypes.FILETIME)).contents
        target.dwLowDateTime = ticks & 0xFFFFFFFF
        target.dwHighDateTime = ticks >> 32
        return 1

    def get_image(self, handle, flags, buffer, size):
        self.assertEqual(handle, self.handle)
        buffer.value = self.image_path
        return 1

    def get_exit(self, handle, code):
        self.assertEqual(handle, self.handle)
        ctypes.cast(code, ctypes.POINTER(sp.wintypes.DWORD)).contents.value = self.exit_code
        return 1

    def probe(self, content):
        self.stream = RecordingStream(content)
        with patch.object(Path, "open", return_value=self.stream) as opened:
            result = self.provider.steam_startup_complete(41)
        opened.assert_called_once_with("rb")
        self.assertTrue(self.stream.closed)
        return result

    def test_current_process_marker_is_accepted_through_query_only_handle(self):
        self.assertTrue(self.probe(OLD_MARKER + MARKER))
        self.native.OpenProcess.assert_called_once_with(0x1000, False, 41)
        self.native.CloseHandle.assert_called_once_with(self.handle)
        self.assertEqual(self.stream.read_sizes, [128 * 1024])

    def test_same_registry_and_log_without_current_marker_is_not_ready(self):
        self.assertFalse(self.probe(OLD_MARKER))

    def test_reused_pid_with_new_creation_cannot_reuse_old_completion(self):
        self.started_at = datetime(2026, 9, 9, 12, 54).timestamp()
        self.assertFalse(self.probe(MARKER))

    def test_future_malformed_or_partial_marker_is_not_ready(self):
        for content in (
            MARKER.replace(b"12:53:18", b"12:59:18"),
            MARKER.replace(b"09-09", b"99-99"),
            MARKER.rstrip(b"\r\n"),
            MARKER.replace(b"13.36", b"nan"),
            b"prefix " + MARKER,
            b"",
        ):
            with self.subTest(content=content):
                self.assertFalse(self.probe(content))

    def test_log_reads_are_bounded_and_truncated_first_line_is_discarded(self):
        self.assertTrue(self.probe(b"x" * (200 * 1024) + b"\n" + MARKER))
        self.assertEqual(self.stream.read_sizes, [128 * 1024])
        # A marker at the tail boundary has no verified line start.
        content = b"x" * 10 + MARKER + b"x" * (128 * 1024 - len(MARKER))
        self.assertFalse(self.probe(content))

    def test_missing_or_denied_log_raises_and_releases_handle(self):
        for error in (FileNotFoundError(), PermissionError()):
            with self.subTest(error=error):
                self.native.CloseHandle.reset_mock()
                with patch.object(Path, "open", side_effect=error), self.assertRaises(OSError):
                    self.provider.steam_startup_complete(41)
                self.native.CloseHandle.assert_called_once_with(self.handle)

    def test_wrong_image_or_exited_process_cannot_pass(self):
        self.image_path = r"C:\Steam\steamwebhelper.exe"
        with patch.object(Path, "open") as opened:
            self.assertFalse(self.provider.steam_startup_complete(41))
        opened.assert_not_called()
        self.image_path = r"C:\Steam\steam.exe"
        self.exit_code = 0
        self.assertFalse(self.probe(MARKER))

    def test_native_query_failures_release_only_acquired_handle(self):
        for function in ("OpenProcess", "GetProcessTimes", "QueryFullProcessImageNameW",
                         "GetExitCodeProcess"):
            with self.subTest(function=function):
                self.native.CloseHandle.reset_mock()
                with patch.object(self.native, function, return_value=0), patch.object(
                    Path, "open", return_value=io.BytesIO(MARKER)
                ), self.assertRaises(OSError):
                    self.provider.steam_startup_complete(41)
                if function == "OpenProcess":
                    self.native.CloseHandle.assert_not_called()
                else:
                    self.native.CloseHandle.assert_called_once_with(self.handle)

    def test_invalid_pid_is_rejected_without_native_access(self):
        for value in (None, True, 0, -1, "41", 2**32):
            with self.subTest(value=value), self.assertRaises(ValueError):
                self.provider.steam_startup_complete(value)
        self.native.OpenProcess.assert_not_called()

    def test_native_signatures_preserve_handle_width_and_filetime_pointers(self):
        # Call the real signature binder against a fake DLL, never kernel32.
        native = Mock()
        with patch.object(sp.ctypes, "WinDLL", return_value=native):
            bound = self.bind_native()
        self.assertIs(bound.OpenProcess.restype, sp.wintypes.HANDLE)
        self.assertEqual(bound.GetProcessTimes.argtypes,
                         (sp.wintypes.HANDLE, *(ctypes.POINTER(sp.wintypes.FILETIME),) * 4))
        self.assertEqual(bound.GetExitCodeProcess.argtypes,
                         (sp.wintypes.HANDLE, ctypes.POINTER(sp.wintypes.DWORD)))


class SteamBranchEnvelopeTests(unittest.IsolatedAsyncioTestCase):
    def setUp(self):
        from tests import test_dayz_test_tool as fixtures
        self.fixtures = fixtures
        self.tool = fixtures.dayz_test_tool
        self.enterContext(patch.object(self.tool, "open_approved_launcher",
                                      return_value=fixtures._Opened()))
        self.enterContext(patch.object(
            self.tool.secure_launcher, "load_verified_bundle",
            return_value=fixtures._Bundle(fixtures._sealed(fixtures._policy())),
        ))
        self.enterContext(patch.object(self.tool, "preflight_vpp_request", return_value=
            SimpleNamespace(error_code=None, missing=(), warnings=(), hint="")))
        self.enterContext(patch.object(self.tool, "evaluate_steam_session", return_value=
            sp.SteamSessionResult("steam_session_stale", 99, (41,), sp.REMEDIATION)))
        self.launch = self.enterContext(patch.object(
            self.tool, "_execute_request", new=AsyncMock(return_value={"status": "succeeded"})
        ))
        self.enterContext(patch.object(
            self.tool.secure_launcher, "execute_secure_launcher_request",
            new=AsyncMock(side_effect=AssertionError("Real launcher forbidden")),
        ))
        self.runtime = fixtures._Runtime()
        self.remediated = SimpleNamespace(
            error_code=None, steam_registered_pid=41, steam_live_pids=(41,),
            remediation=sp.REMEDIATION, steam_pid_repair_reason="applied",
            steam_restart_fallback=False, steam_left_down=False,
            steam_remediation_reason=None, active_user=987654321,
            steam_previous_registered_pid=99, steam_pid_repair_target_pid=41,
        )
        self.remediation = self.enterContext(patch.object(
            sp, "remediate_stale_steam_session", return_value=self.remediated
        ))

    async def run_tool(self, *, extension=False, **kwargs):
        return await self.tool.execute_dayz_test_run(
            self.runtime, project="ExampleMod", mode="client" if extension else "all",
            run_id=self.fixtures.RUN_ID if extension else None,
            extra_mods=["@DayZ_MCP"], auto_remediate_steam=True, **kwargs,
        )

    async def test_stale_opt_in_never_invokes_public_remediation(self):
        # A remediator configured to fail must remain completely uncalled:
        # only daemon admission can decide whether any mutation is allowed.
        self.remediation.side_effect = AssertionError("public mutation forbidden")
        result = await self.run_tool()
        self.assertEqual(result["status"], "succeeded")
        self.remediation.assert_not_called()
        self.assertNotIn("steam_remediated", result)
        self.launch.assert_awaited_once()

    async def test_non_extensible_run_refuses_without_touching_steam(self):
        self.runtime.lifecycle = {"runs": [{
            "run_id": self.fixtures.RUN_ID, "state": "RUNNING", "mod": "@ExampleMod",
        }]}
        result = await self.run_tool(extension=True)
        self.assertEqual(result["error_code"], "run_not_extensible")
        self.launch.assert_not_awaited()
        self.remediation.assert_not_called()

    async def test_client_replacement_refuses_without_touching_steam(self):
        self.runtime.lifecycle = {"runs": [{
            "run_id": self.fixtures.RUN_ID, "state": "RUNNING_IDLE", "mod": "@ExampleMod",
            "profiles": r"P:\ExampleMod_Suite\_client\profiles",
        }]}
        decision = self.tool.ClientReplacementDecision(False, "client_polling", 0.1, 60.0)
        with patch.object(self.tool, "_decide_client_replacement", return_value=decision):
            result = await self.run_tool(extension=True)
        self.assertEqual(result["error_code"], "client_already_polling")
        self.launch.assert_not_awaited()
        self.remediation.assert_not_called()

    async def test_preflight_never_reads_or_repairs_steam(self):
        with patch.object(self.tool, "evaluate_steam_session") as evaluate:
            result = await self.run_tool(preflight=True)
        evaluate.assert_not_called()
        self.remediation.assert_not_called()
        self.assertIn("steam_session", result["preflight_skipped_checks"])


if __name__ == "__main__":
    unittest.main()
